/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package cn.myera.whurec.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2015-4-21")
public class BookPref implements org.apache.thrift.TBase<BookPref, BookPref._Fields>, java.io.Serializable, Cloneable, Comparable<BookPref> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("BookPref");

  private static final org.apache.thrift.protocol.TField BOOK_MODEL_ORDER_FIELD_DESC = new org.apache.thrift.protocol.TField("book_model_order", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField PREF_FIELD_DESC = new org.apache.thrift.protocol.TField("pref", org.apache.thrift.protocol.TType.DOUBLE, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new BookPrefStandardSchemeFactory());
    schemes.put(TupleScheme.class, new BookPrefTupleSchemeFactory());
  }

  public int book_model_order; // required
  public double pref; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    BOOK_MODEL_ORDER((short)1, "book_model_order"),
    PREF((short)2, "pref");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // BOOK_MODEL_ORDER
          return BOOK_MODEL_ORDER;
        case 2: // PREF
          return PREF;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __BOOK_MODEL_ORDER_ISSET_ID = 0;
  private static final int __PREF_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.BOOK_MODEL_ORDER, new org.apache.thrift.meta_data.FieldMetaData("book_model_order", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.PREF, new org.apache.thrift.meta_data.FieldMetaData("pref", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(BookPref.class, metaDataMap);
  }

  public BookPref() {
  }

  public BookPref(
    int book_model_order,
    double pref)
  {
    this();
    this.book_model_order = book_model_order;
    setBook_model_orderIsSet(true);
    this.pref = pref;
    setPrefIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public BookPref(BookPref other) {
    __isset_bitfield = other.__isset_bitfield;
    this.book_model_order = other.book_model_order;
    this.pref = other.pref;
  }

  public BookPref deepCopy() {
    return new BookPref(this);
  }

  @Override
  public void clear() {
    setBook_model_orderIsSet(false);
    this.book_model_order = 0;
    setPrefIsSet(false);
    this.pref = 0.0;
  }

  public int getBook_model_order() {
    return this.book_model_order;
  }

  public BookPref setBook_model_order(int book_model_order) {
    this.book_model_order = book_model_order;
    setBook_model_orderIsSet(true);
    return this;
  }

  public void unsetBook_model_order() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __BOOK_MODEL_ORDER_ISSET_ID);
  }

  /** Returns true if field book_model_order is set (has been assigned a value) and false otherwise */
  public boolean isSetBook_model_order() {
    return EncodingUtils.testBit(__isset_bitfield, __BOOK_MODEL_ORDER_ISSET_ID);
  }

  public void setBook_model_orderIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __BOOK_MODEL_ORDER_ISSET_ID, value);
  }

  public double getPref() {
    return this.pref;
  }

  public BookPref setPref(double pref) {
    this.pref = pref;
    setPrefIsSet(true);
    return this;
  }

  public void unsetPref() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __PREF_ISSET_ID);
  }

  /** Returns true if field pref is set (has been assigned a value) and false otherwise */
  public boolean isSetPref() {
    return EncodingUtils.testBit(__isset_bitfield, __PREF_ISSET_ID);
  }

  public void setPrefIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __PREF_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case BOOK_MODEL_ORDER:
      if (value == null) {
        unsetBook_model_order();
      } else {
        setBook_model_order((Integer)value);
      }
      break;

    case PREF:
      if (value == null) {
        unsetPref();
      } else {
        setPref((Double)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case BOOK_MODEL_ORDER:
      return Integer.valueOf(getBook_model_order());

    case PREF:
      return Double.valueOf(getPref());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case BOOK_MODEL_ORDER:
      return isSetBook_model_order();
    case PREF:
      return isSetPref();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof BookPref)
      return this.equals((BookPref)that);
    return false;
  }

  public boolean equals(BookPref that) {
    if (that == null)
      return false;

    boolean this_present_book_model_order = true;
    boolean that_present_book_model_order = true;
    if (this_present_book_model_order || that_present_book_model_order) {
      if (!(this_present_book_model_order && that_present_book_model_order))
        return false;
      if (this.book_model_order != that.book_model_order)
        return false;
    }

    boolean this_present_pref = true;
    boolean that_present_pref = true;
    if (this_present_pref || that_present_pref) {
      if (!(this_present_pref && that_present_pref))
        return false;
      if (this.pref != that.pref)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_book_model_order = true;
    list.add(present_book_model_order);
    if (present_book_model_order)
      list.add(book_model_order);

    boolean present_pref = true;
    list.add(present_pref);
    if (present_pref)
      list.add(pref);

    return list.hashCode();
  }

  @Override
  public int compareTo(BookPref other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetBook_model_order()).compareTo(other.isSetBook_model_order());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBook_model_order()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.book_model_order, other.book_model_order);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPref()).compareTo(other.isSetPref());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPref()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.pref, other.pref);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("BookPref(");
    boolean first = true;

    sb.append("book_model_order:");
    sb.append(this.book_model_order);
    first = false;
    if (!first) sb.append(", ");
    sb.append("pref:");
    sb.append(this.pref);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class BookPrefStandardSchemeFactory implements SchemeFactory {
    public BookPrefStandardScheme getScheme() {
      return new BookPrefStandardScheme();
    }
  }

  private static class BookPrefStandardScheme extends StandardScheme<BookPref> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, BookPref struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // BOOK_MODEL_ORDER
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.book_model_order = iprot.readI32();
              struct.setBook_model_orderIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PREF
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.pref = iprot.readDouble();
              struct.setPrefIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, BookPref struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(BOOK_MODEL_ORDER_FIELD_DESC);
      oprot.writeI32(struct.book_model_order);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(PREF_FIELD_DESC);
      oprot.writeDouble(struct.pref);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class BookPrefTupleSchemeFactory implements SchemeFactory {
    public BookPrefTupleScheme getScheme() {
      return new BookPrefTupleScheme();
    }
  }

  private static class BookPrefTupleScheme extends TupleScheme<BookPref> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, BookPref struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetBook_model_order()) {
        optionals.set(0);
      }
      if (struct.isSetPref()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetBook_model_order()) {
        oprot.writeI32(struct.book_model_order);
      }
      if (struct.isSetPref()) {
        oprot.writeDouble(struct.pref);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, BookPref struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.book_model_order = iprot.readI32();
        struct.setBook_model_orderIsSet(true);
      }
      if (incoming.get(1)) {
        struct.pref = iprot.readDouble();
        struct.setPrefIsSet(true);
      }
    }
  }

}

